# Generated by Django 4.1 on 2022-08-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='content',
        ),
    ]
