# Generated by Django 4.1 on 2022-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remeapp', '0002_rename_name_tags_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='cells',
        ),
        migrations.AddField(
            model_name='cells',
            name='tags',
            field=models.ManyToManyField(to='remeapp.tags'),
        ),
    ]
