# Generated by Django 4.1 on 2022-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remeapp', '0003_remove_tags_cells_cells_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='content',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='cells',
            name='tags',
            field=models.ManyToManyField(blank=True, to='remeapp.tags'),
        ),
    ]
