# Generated by Django 4.1 on 2022-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remeapp', '0004_rename_content_tags_name_alter_cells_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cells',
            name='tags',
            field=models.ManyToManyField(to='remeapp.tags'),
        ),
    ]
